# Generated by Django 4.2.23 on 2025-09-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileimage',
            options={'ordering': ['profile_id', 'kind', 'position']},
        ),
        migrations.AddIndex(
            model_name='profileimage',
            index=models.Index(fields=['profile', 'kind', 'position'], name='pages_profi_profile_48eaeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='profileimage',
            constraint=models.UniqueConstraint(fields=('profile', 'kind', 'image'), name='uniq_profile_kind_image'),
        ),
        migrations.AddConstraint(
            model_name='profileimage',
            constraint=models.CheckConstraint(check=models.Q(('image', ''), _negated=True), name='profileimage_image_not_blank'),
        ),
    ]
