# Generated by Django 4.2.23 on 2025-09-06 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_profileimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('seeking', models.TextField(blank=True)),
                ('relationship_status', models.CharField(blank=True, max_length=50)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('children', models.CharField(blank=True, max_length=50)),
                ('smoker', models.CharField(blank=True, max_length=20)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extras', to='pages.profile')),
            ],
        ),
    ]
