# Generated by Django 4.2.23 on 2025-09-09 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0007_marketinglead'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_seen_hotdate_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MessageThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_a', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads_as_b', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='pages.messagethread')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HotDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('details', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hot_dates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['user_a', 'user_b'], name='pages_messa_user_a__1d253f_idx'),
        ),
        migrations.AddIndex(
            model_name='messagethread',
            index=models.Index(fields=['updated_at'], name='pages_messa_updated_b4eab4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagethread',
            unique_together={('user_a', 'user_b')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'id'], name='pages_messa_thread__17e082_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='pages_messa_thread__06d0de_idx'),
        ),
        migrations.AddIndex(
            model_name='hotdate',
            index=models.Index(fields=['starts_at', 'expires_at'], name='pages_hotda_starts__e48d47_idx'),
        ),
        migrations.AddIndex(
            model_name='hotdate',
            index=models.Index(fields=['updated_at'], name='pages_hotda_updated_cc7dff_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'target'], name='pages_favor_user_id_439caa_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['target', 'created_at'], name='pages_favor_target__8c9255_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'target')},
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['blocker', 'blocked'], name='pages_block_blocker_99791b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('blocker', 'blocked')},
        ),
    ]
